### ISSUE TITLE
running test fails

### ISSUE THREAD

**Issue by waozixyz** [ipfs-shipyard/peer-crdt-ipfs#1]
running the test gives me the following error log:
```
$ mocha test


  basic
    ✓ can be created
    ✓ can be applied to peer-crdt
Swarm listening on /ip4/127.0.0.1/tcp/46533/ipfs/QmVjkjEG2PkSEZRPPhdFz34V8S46vwdsMXSMhzoitmMCbv
    ✓ CRDT network can be started (118ms)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.it (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:76:10)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.it (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:76:10)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
    1) converges
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:92:10)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:92:10)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:93:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:93:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:94:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/basic.spec.js:94:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
    2) mirrors embeds
    ✓ CRDT network can be stopped

  swarm
Swarm listening on /ip4/127.0.0.1/tcp/41379/ipfs/QmbRVj8QJ7ccrkBpchtY2mbVUyS9PvBnUnqgxx5d2t7zBo
Swarm listening on /ip4/127.0.0.1/tcp/35677/ipfs/Qmac44ZgcJaxicWhEHvaNw7vrmWcA3bM7WJ2fircJK2a6s
Swarm listening on /ip4/127.0.0.1/tcp/33097/ipfs/QmbK3DpH5pZsUCGCk4m8CotdVYnorFgBU83tirS2ezjwep
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
TypeError: this._options.encrypt is not a function
    at Log._encrypt (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:298:26)
    at Log.append (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/log/index.js:27:39)
    at EventEmitter.methods.(anonymous function)._args [as push] (/home/wolfi/peer-crdt-ipfs/node_modules/peer-crdt/src/crdt/type.js:38:15)
    at nodes.forEach (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:41)
    at Array.forEach (<anonymous>)
    at Context.<anonymous> (/home/wolfi/peer-crdt-ipfs/test/swarm.spec.js:52:11)
    at callFnAsync (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:377:21)
    at Test.Runnable.run (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runnable.js:324:7)
    at Runner.runTest (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:442:10)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:560:12
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:356:14)
    at /home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:366:7
    at next (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:290:14)
    at Immediate.<anonymous> (/home/wolfi/peer-crdt-ipfs/node_modules/mocha/lib/runner.js:334:5)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
    3) CRDT converges


  4 passing (35s)
  3 failing

  1) basic
       converges:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) basic
       mirrors embeds:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) swarm
       CRDT converges:

      Uncaught AssertionError: expected [] to deeply equal [ 0, 1, 2 ]
      + expected - actual

      -[]
      +[
      +  0
      +  1
      +  2
      +]
      
      at Timeout.setTimeout [as _onTimeout] (test/swarm.spec.js:64:37)

```

**Comment by pgte** [comment]
Should be ok, but please reopen this if you're having issues again.
